version: '2'
services:
  mongo:
    image: mongo:4.4.3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - mychat-mongo:/data/db
    expose:
      - 27017
    ports:
      - 57011:27017
