version: '2'
services:
  mongo:
    image: mongo:4.4.3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - 57025:27017
    volumes:
      - /data/mychat/mongodb:/data/db

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    environment:
      - COOKIE_SECRET=qwerty
      - TOKEN_SECRET=qwerty
      - CORS_ORIGIN=*
      - MONGO_URL=mongodb://mongo:27017/mychat
    ports:
      - 26502:3001

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile.prod
    ports:
      - 26501:3000

networks:
  default:
    external:
      name: bridge-mychat
