version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - "57025:27017"
    volumes:
      - /data/mychat/mongodb:/data/db

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    environment:
      - COOKIE_SECRET=qwerty
      - TOKEN_SECRET=qwerty
      - CORS_ORIGIN=*
      - MONGO_URL=mongodb://mongo:27017/mychat
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    restart: always
    ports:
      - "26502:3001"

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "26501:3000"

  redis:
    image: redis:6.2.7-alpine
    restart: always
    command: redis-server
    ports:
      - "57012:6379"

  caddy:
    image: livekit/caddyl4
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit/caddy.yaml:/etc/caddy.yaml
      - ./livekit/caddy_data:/data

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml

networks:
  default:
    external:
      name: bridge-mychat
