version: '2'
services:
  mongo:
    image: mongo
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - 57025:27017
    volumes:
      - /data/mychat/mongodb:/data/db

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    environment:
      - COOKIE_SECRET=qwerty
      - TOKEN_SECRET=qwerty
      - CORS_ORIGIN=*
      - MONGO_URL=mongodb://mongo:27017/mychat
    restart: always
    ports:
      - 26502:3001

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 26501:3000

  mongoExpress:
    ports:
      - 26505:8081
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_SITE_BASEURL=/db/

  redis:
    image: redis:6.2.1-alpine
    restart: always
    command: redis-server
    ports:
      - 57012:6379
networks:
  default:
    external:
      name: bridge-mychat
