version: '2'
services:
  mongo:
    image: mongo:5.0.6
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    expose:
      - 27017
    ports:
      - 57011:27017

  redis:
    image: redis:6.2.1-alpine
    restart: always
    command: redis-server
    ports:
      - 57012:6379

  mongo-livelists:
    image: mongo:6.0.3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]
    expose:
      - 27017
    ports:
      - "57017:27017"

  redis-livelists:
    image: redis:7.0.5-alpine
    restart: always
    command: redis-server
    ports:
      - 57013:6379

  livelists-server:
    image: nikrainev/livelists-server:0.1.5
    restart: always
    command: livelists-server
    volumes:
      - /Users/nikitakrainev/Desktop/LiveLists/mychat/livelists/config.yaml:/config.yaml
    ports:
      - 7771:7771
      - 8080:8080

  redis-stack-livelists:
    image: redis/redis-stack:latest
    restart: always
    command: redis-server
    ports:
      - 57014:6379
