version: '2'
services:
  mongo:
    image: mongo:4.4.3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    expose:
      - 27017
    ports:
      - 57011:27017

  redis:
    image: redis:6.2.1-alpine
    restart: always
    command: redis-server
    ports:
      - 57012:6379
