exports.CHAT__V1_NEW_MESSAGE_POSTED  = 'chat/V1_NEW_MESSAGE_POSTED';

exports.VIDEO_CONF__V1_SUCCESS_JOIN = 'videoConf/V1_SUCCESS_JOIN';
exports.VIDEO_CONF__V1_NEW_PARTICIPANT = 'videoConf/V1_NEW_PARTICIPANT';
exports.VIDEO_CONF__V1_PARTICIPANT_LEAVE = 'videoConf/V1_PARTICIPANT_LEAVE';
exports.VIDEO_CONF_NEW_SDP_OFFER = 'videoConf/V1_NEW_SDP_OFFER';
