#cloud-config
# This file is used as a user-data script to start a VM
# It'll upload configs to the right location and install LiveKit as a systemd service
# LiveKit will be started automatically at machine startup
package_update: true
package_upgrade: all

packages:
  - docker.io

bootcmd:
  - mkdir -p /opt/livekit/caddy_data
  - mkdir -p /usr/local/bin

write_files:
  - path: /opt/livekit/livekit.yaml
    content: |
      port: 7880
      rtc:
          tcp_port: 7881
          port_range_start: 50000
          port_range_end: 60000
          use_external_ip: true
      redis:
          address: redis:6379
          username: ""
          password: ""
          db: 0
      turn:
          enabled: true
          domain: mychat-livekit-turn.whats-better.fun
          cert_file: ""
          key_file: ""
          tls_port: 5349
          udp_port: 443
          external_tls: true
      keys:
          APIhGpMrs73Fu9W: ad1Omw31DWd1F8b8oFkMbAdt9Jc5yKxe7zj5nPwtU6e
      

  - path: /opt/livekit/caddy.yaml
    content: |
      logging:
        logs:
          default:
            level: INFO
      storage:
        "module": "file_system"
        "root": "/data"
      apps:
        tls:
          certificates:
            automate:
              - mychat-livekit.whats-better.fun
              - mychat-livekit-turn.whats-better.fun
        layer4:
          servers:
            main:
              listen: [":443"]
              routes:
                - match:
                  - tls:
                      sni:
                        - "mychat-livekit-turn.whats-better.fun"
                  handle:
                    - handler: tls
                    - handler: proxy
                      upstreams:
                        - dial: ["localhost:5349"]
                - match:
                    - tls:
                        sni:
                          - "mychat-livekit.whats-better.fun"
                  handle:
                    - handler: tls
                      connection_policies:
                        - alpn: ["http/1.1"]
                    - handler: proxy
                      upstreams:
                        - dial: ["localhost:7880"]

  - path: /opt/livekit/update_ip.sh
    content: |
      #!/usr/bin/env bash
      ip=`ip addr show |grep "inet " |grep -v 127.0.0. |head -1|cut -d" " -f6|cut -d/ -f1`
      sed -i.orig -r "s/\\\"(.+)(\:5349)/\\\"$ip\2/" /opt/livekit/caddy.yaml
      

  - path: /opt/livekit/docker-compose.yaml
    content: |
      # LiveKit requires host networking, which is only available on Linux
      # This compose will not function correctly on Mac or Windows
      version: "3.9"
      services:
        caddy:
          image: livekit/caddyl4
          command: run --config /etc/caddy.yaml --adapter yaml
          restart: unless-stopped
          network_mode: "host"
          volumes:
            - ./caddy.yaml:/etc/caddy.yaml
            - ./caddy_data:/data
        livekit:
          image: livekit/livekit-server:latest
          command: --config /etc/livekit.yaml
          restart: unless-stopped
          network_mode: "host"
          volumes:
            - ./livekit.yaml:/etc/livekit.yaml
      

  - path: /etc/systemd/system/livekit-docker.service
    content: |
      [Unit]
      Description=LiveKit Server Container
      After=docker.service
      Requires=docker.service
      
      [Service]
      LimitNOFILE=500000
      Restart=always
      WorkingDirectory=/opt/livekit
      # Shutdown container (if running) when unit is started
      ExecStartPre=/usr/local/bin/docker-compose -f docker-compose.yaml down
      ExecStart=/usr/local/bin/docker-compose -f docker-compose.yaml up
      ExecStop=/usr/local/bin/docker-compose -f docker-compose.yaml down
      
      [Install]
      WantedBy=multi-user.target
      


runcmd:
  - curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod 755 /usr/local/bin/docker-compose
  - chmod 755 /opt/livekit/update_ip.sh
  - /opt/livekit/update_ip.sh
  - systemctl enable livekit-docker
  - systemctl start livekit-docker
