name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted
    env:
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      TOKEN_SECRET: ${{ secrets.TOKEN_TOKEN }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      MONGO_URL: ${{ secrets.MONGO_URL }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose --compatibility -f -e MONGO_URL docker-compose.server.yml up -d --force-recreate --build
